config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :tags
  resources :posts do
    get :top, :fresh, on: :collection
    member do
      put "like", to: "posts#like"
      put "favorite", to: "posts#favorite"
      put "unfavorite", to: "posts#unfavorite"
    end
  end

  root 'posts#top'
  get 'static_pages/index'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true
  has_rich_text :content
  belongs_to :user
  acts_as_votable
  validates :title, length: { maximum: 70 }
  validates :content, length: { maximum: 10000 }
	has_many :post_tags, inverse_of: :post, dependent: :destroy
	has_many :tags, through: :post_tags

end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :tag, counter_cache: true
  belongs_to :post
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :post_tags
	has_many :posts, through: :post_tags
	validates :name, length: {minimum: 1, maximum: 25}, uniqueness: true
	def to_s
		name
	end
	def popular_name
	  "#{name.to_s}: #{post_tags_count.to_s}"
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(access_token)
      data = access_token.info
      user = User.where(email: data['email']).first
  
      # Uncomment the section below if you want users to be created if they don't exist
      unless user
         user = User.create(
            email: data['email'],
            name: access_token.info.name,
            image: access_token.info.image,
            provider: access_token.provider,
            uid: access_token.uid,
            token: access_token.credentials.token,
            expires_at: access_token.credentials.expires_at,
            expires: access_token.credentials.expires,
            refresh_token: access_token.credentials.refresh_token,
            password: Devise.friendly_token[0,20],
         )
      else #if user account exists - add additional data
        user.name = access_token.info.name
        user.image = access_token.info.image
        user.provider = access_token.provider
        user.uid = access_token.uid
        user.token = access_token.credentials.token
        user.expires_at = access_token.credentials.expires_at
        user.expires = access_token.credentials.expires
        user.refresh_token = access_token.credentials.refresh_token
        user.save!
      end
      user
  end
  has_many :posts
  acts_as_voter

  def username
    self.email.split(/@/).first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :top, :fresh]
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]

  def index
    #@posts = Post.all
    redirect_to fresh_posts_path
  end
  
  def top
    @posts = Post.all.order(cached_votes_score: :desc)
    render 'index'
  end
  
  def fresh
    @posts = Post.all.order(created_at: :desc)
    render 'index'
  end

  def show
  end

  def like
    if current_user.voted_up_on? @post
      @post.downvote_by current_user
    elsif current_user.voted_down_on? @post
      @post.upvote_by current_user
    else #not voted
      @post.upvote_by current_user
    end
    respond_to do |format|
     format.js
    end 
  end

  def new
    @post = Post.new
  end

  def edit
    if @post.user_id == current_user.id
      #OK
    else
      redirect_to root_path, notice: 'You are not authorized!'
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @post.user_id == current_user.id
      respond_to do |format|
        if @post.update(post_params)
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { render :show, status: :ok, location: @post }
        else
          format.html { render :edit }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path, notice: 'У вас нет прав!'
    end
  end

  def destroy
    if @post.user_id == current_user.id
      @post.destroy
      respond_to do |format|
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      redirect_to root_path, notice: 'You are not authorized!'
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, tag_ids: [])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:privacy_policy]

  def index
  end
  
  def privacy_policy
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      render json: @tag
    else
      render json: {errors: @tag.errors.full_messages}
    end
  end
  private
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-success.sticky-top
  %a.navbar-brand{:href => "/posts/fresh"} 
    = image_tag 'pikabu-555161.png', size: '20x20'
    Pikaburuby
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item{class: "#{'active font-weight-bold' if current_page?(top_posts_path)}"}
        = link_to top_posts_path, class: 'nav-link' do
          .fa.fa-fire
          Top
      %li.nav-item{class: "#{'active font-weight-bold' if current_page?(fresh_posts_path)}"}
        = link_to fresh_posts_path, class: 'nav-link' do
          .far.fa-clock
          Fresh
      /%li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_post_path)}"}
      /  = link_to new_post_path, class: 'nav-link' do
      /    .fa.fa-plus
      /    Create
    %ul.navbar-nav.mr-right
      - if current_user
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(edit_user_registration_path)}"}
          = link_to edit_user_registration_path, class: 'nav-link' do
            - if current_user.image?
              = image_tag current_user.image, size: '30x30', alt: "#{current_user.email}", class: 'rounded-circle'
            - else
              .fa.fa-user
            = current_user.username
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(destroy_user_session_path)}"}
          = link_to destroy_user_session_path, method: :delete, class: 'nav-link' do
            .fa.fa-sign-out-alt
            Log out
      - else
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_registration_path)}"}
          = link_to 'Register', new_user_registration_path, class: 'nav-link'
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_user_session_path)}"}
          = link_to 'Login', new_user_session_path, class: 'nav-link'
        /%li.nav-item{class: "#{'active font-weight-bold' if current_page?(privacy_policy_path)}"}
        /  = link_to 'Политика Конфиденциальности', privacy_policy_path, class: 'nav-link'
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(user_google_oauth2_omniauth_authorize_path)}"}
          = link_to user_google_oauth2_omniauth_authorize_path, class: 'nav-link' do
            .fab.fa-google

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pikaburuby
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'pikabu-555161.png'
  %body#body-human
    = render 'layouts/header'
    .container
      %p
      = render 'layouts/messages'
      .row
        .col-md-8
          = yield
        .col-md-4
          - if current_user
            = link_to new_post_path, class: 'btn btn-block btn-success' do
              .fa.fa-plus
              New Post
            %p
          .btn.btn-info.btn-block.disabled
            .fa.fa-user
            Users:
            %span.badge.badge-light
              = User.count
          %p
          .btn.btn-info.btn-block.disabled
            .fa.fa-fire
            Posts:
            %span.badge.badge-light
              = Post.count
          %p
          .btn.btn-info.btn-block.disabled
            .fa.fa-thumbs-up
            Votes:
            %span.badge.badge-light
              = ActsAsVotable::Vote.count
          %p

app/views/posts/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@post) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :content, as: :rich_text_area
    /= f.rich_text_area :content
    = f.label :tags
    = f.select :tag_ids, Tag.all.pluck(:name, :id), {}, { multiple: true, class: "selectize-tags" }

  .form-actions
    = f.button :submit

app/views/posts/_like_link.html.haml
= link_to like_post_path(post), method: :put, remote: true, id: "like-link-#{post.id}", class: 'btn' do
  - if current_user.voted_up_on?(post)
    .text-success.fa.fa-thumbs-up
    %b= post.cached_votes_score
    .text-secondary.fa.fa-thumbs-down
  - elsif current_user.voted_down_on?(post)
    .text-secondary.fa.fa-thumbs-up
    %b= post.cached_votes_score
    .text-danger.fa.fa-thumbs-down
  - else
    .text-secondary.fa.fa-thumbs-up
    %b= post.cached_votes_score
    .text-secondary.fa.fa-thumbs-down

app/views/posts/_likes.html.haml
/= pluralize(@post.cached_votes_score, "like")
.fa.fa-heart
%b= @post.cached_votes_score

app/views/posts/_post.html.haml
.card
  .card-header
    = link_to post.title, post
    /= post.title
  .card-body
    = post.content
  .card-footer
    %small
      = post.created_at.strftime('%H:%M, %d.%m.%y')
      .float-right
        - if post.user.image?
          = image_tag post.user.image, size: '30x30', alt: "#{post.user.username}", class: 'rounded-circle'
        = post.user.username

  .card-footer.text-center
    - if current_user
      = content_tag "div", id: "like-link-#{post.id}" do
        = render 'posts/like_link', post: post
    - else
      %b= post.cached_votes_score

  - if post.tags.any?
    .card-footer
      - post.tags.each do |tag|
        .badge.badge-info
          = tag.name


  - if current_user
    - if post.user == current_user
      .card-footer.text-center
        /= link_to 'Показать', post
        /= link_to 'Редактировать', edit_post_path(post)
        .btn-group
          = link_to edit_post_path(post), class: 'btn btn-sm btn-warning' do
            .fa.fa-edit
            Редактировать
          = link_to post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do
            .fa.fa-trash
            Удалить

%p

app/views/posts/edit.html.haml
.card
  .card-header
    %h3 Редактировать
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Назад', @post

app/views/posts/index.html.haml
/%h3
/  Все посты:
/  = @posts.count

- @posts.each do |post|
  = render 'posts/post', post: post

app/views/posts/like.js.haml
$('#like-link-#{@post.id}').replaceWith('#{escape_javascript render 'posts/like_link', post: @post}');

app/views/posts/new.html.haml
.card
  .card-header
    %h3 Создать
  .card-body
    = render 'form'
  .card-footer
    = link_to 'Назад', posts_path

app/views/posts/show.html.haml
= render 'posts/post', post: @post

= link_to 'Назад', posts_path

app/views/static_pages/index.html.haml
.jumbotron.bg-danger
  %h1 Всем привет!
  %p Find me in app/views/static_pages/index.html.erb
  %button.btn.btn-primary{:type => "button"} Primary

.fab.fa-amazon
.fa.fa-flag
.fa.fa-home
.fa.fa-user
= link_to 'Домой', root_path
= link_to root_path, class: 'btn btn-primary' do
  %h1
    .fa.fa-home
    Домой

app/views/static_pages/privacy_policy.html.haml
%h2 Privacy Policy
%p
  Your privacy is important to us. It is pikaburuby's policy to respect your privacy regarding any information we may collect from you across our website,
  = succeed "," do
    %a{:href => "https://pikaburuby.herokuapp.com"} http://pikaburuby.herokuapp.com
%p We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used.
%p We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorized access, disclosure, copying, use or modification.
%p We don’t share any personally identifying information publicly or with third-parties, except when required to by law.
%p Our website may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies.
%p You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services.
%p Your continued use of our website will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.
%p This policy is effective as of 24 April 2020.